frontend/website1/Project/Project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapi', include('webapi.urls')),
    path('', include('baseportal.urls')),
]

frontend/website1/Project/baseportal/urls.py
from django.urls.conf import path
from baseportal.views import HomePageView, LandRecordView

app_name='baseportal'

urlpatterns=[
    path('', HomePageView.as_view(), name='homepage'),
    path('landrecord', LandRecordView.as_view(), name='landrecord')
]

frontend/website1/Project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapi', include('webapi.urls')),
    path('', include('baseportal.urls')),
]

frontend/website1/Project/webapi/urls.py
import webapi.views as views
from rest_framework import routers
from django.conf.urls import url, include

app_name="webapi"

router = routers.DefaultRouter()
router.register(r'district', views.DistrictViewSet)
router.register(r'taluk', views.TalukViewSet)
router.register(r'grampanchayat', views.GramPanchayatViewSet)

urlpatterns=[
    url(r'^/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

frontend/website1/Project/baseportal/models.py
from django.db import models

# Create your models here.

class District(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name



class Taluk(models.Model):
    name=models.CharField(max_length=50)
    district=models.ForeignKey(District, on_delete=models.CASCADE)
    def __str__(self):
        return self.name



class GramPanchayat(models.Model):
    name=models.CharField(max_length=50)
    taluk=models.ForeignKey(Taluk, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

frontend/website1/Project/webapi/models.py
from django.db import models

# Create your models here.

frontend/website1/Project/baseportal/forms.py
from django.forms import forms
from django import forms
from baseportal.models import District, Taluk, GramPanchayat
from django.forms.utils import ErrorList

class LandForm(forms.Form):
    district=forms.ModelChoiceField(queryset=District.objects.all(), 
                                    widget=forms.Select(attrs={"onChange":"getDistrict(this.value)"})
                                    )
    taluk=forms.ModelChoiceField(queryset=Taluk.objects.all(),
                                 widget=forms.Select(attrs={"onChange":"getTaluk(this.value)"})
                                )
    gram_panchayat=forms.ModelChoiceField(queryset=GramPanchayat.objects.all())
    land_number=forms.CharField()
    

frontend/website1/Project/baseportal/views.py
from django.shortcuts import render
from django.views.generic.base import View
from baseportal.forms import LandForm

from web3 import Web3, HTTPProvider
from Project.settings import trufSettings
from web3.contract import ConciseContract


web3 = Web3(HTTPProvider(trufSettings["server"]))

Bhoomi=web3.eth.contract(abi=trufSettings["abi"], address=trufSettings["address"])


# Create your views here.
class HomePageView(View):
    def get(self, request):
        return render(request, "baseportal/homepage.html")

class LandRecordView(View):
    def get(self, request):
        context={
            "form":LandForm()
        }
        return render(request, "baseportal/landrecord.html", context)
    def post(self, request):
        form=LandForm(request.POST)
        context={
            "form":form,
        }
        if form.is_valid():
            landno=int(form.cleaned_data["land_number"])
            partinfo=form.cleaned_data["gram_panchayat"].id
            print("landno",landno,"partinfo",partinfo)
            lotno=int("{:05d}{:05d}".format(partinfo, landno))
            print("checking",lotno)
            name, aadhar, pan=Bhoomi.call().getOwner(lotno)
            context["result"]={
                "lotno":lotno,
                "name":name,
                "aadhar":aadhar,
                "pan":pan
            }
            
        return render(request, "baseportal/landrecord.html", context)
    
        

frontend/website1/Project/webapi/views.py
from django.shortcuts import render
from rest_framework.viewsets import ReadOnlyModelViewSet
from webapi.serializers import DistrictSerializer, TalukSerializer,\
    GramPanchayatSerializer
from baseportal.models import District, Taluk, GramPanchayat

# Create your views here.

class DistrictViewSet(ReadOnlyModelViewSet):
    queryset=District.objects.all()
    serializer_class=DistrictSerializer


class TalukViewSet(ReadOnlyModelViewSet):
    queryset=Taluk.objects.all()
    serializer_class=TalukSerializer
    filter_fields=('district',)


class GramPanchayatViewSet(ReadOnlyModelViewSet):
    queryset=GramPanchayat.objects.all()
    serializer_class=GramPanchayatSerializer
    filter_fields=('taluk',)
    

frontend/website1/Project/baseportal/templates/base.html
<!DOCTYPE html>
<head>
<!--
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Seller</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous"></script>
-->
<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!--<script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>-->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



  {% block head %}{% endblock %}


  <style>
    h3, h4 {
        margin: 10px 0 30px 0;
        letter-spacing: 10px;
        font-size: 20px;
        color: #111;
    }



    .carousel-caption h3 {
        color: #fff !important;
    }
    @media (max-width: 600px) {
      .carousel-caption {
        display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */
      }
    }

    .thumbnail {
        padding: 0 0 15px 0;
        border: none;
        border-radius: 0;
    }
    .thumbnail p {
        margin-top: 15px;
        color: #555;
    }




    .btn {
        padding: 10px 20px;
        background-color: #333;
        color: #f1f1f1;
        border-radius: 0;
        transition: .2s;
    }
    .btn:hover, .btn:focus {
        border: 1px solid #333;
        background-color: #fff;
        color: #000;
    }
    .modal-header, h4, .close {
        background-color: #27bf38;
        color: #fff !important;
        text-align: center;
        font-size: 30px;
    }
    .modal-header, .modal-body {
        padding: 40px 50px;
    }
    </style>

</head>
<body>
 <div class="container">
   {% block navbar %}

     {% endblock %}
 	{% block content %}{% endblock %}
 </div>
</body>

frontend/website1/Project/baseportal/templates/baseportal/homepage.html
{% extends 'base.html' %}
{% load static %}


        {% block head %}



        <script>
        {% include 'baseportal/scroll.js' %}
        </script>
        {% block navbar %}
        <div class="navbar-wrapper" >
            <div class="container-fluid">


        <nav class="navbar navbar-inverse navbar-fixed-top">

            <a class="navbar-brand" href="#">Real Time Record Maintenance</a>
          <!--<div class="container">
                </div>-->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav navbar-right" style="margin-right:1px">



                            <li class="active"><a href="{% url 'baseportal:landrecord' %}"><span class="glyphicon glyphicon-file"></span> Land Records</a></li>
                        <!--    <li><a href="#product1"><span class="glyphicon glyphicon-shopping-cart"></span> Product</a></li>
                            <li><a href="#about"><i class="fa fa-users"></i> About</a></li>
                            <li><a href="#contact"><i class="fa fa-address-card-o"></i> Contact</a></li>
-->
                    <!--        {% if user.is_authenticated %}
                            <ul class="nav navbar-nav navbar-right">
                             <li><a href="{% url 'accounts:signup' %}"> <span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="{% url 'accounts:loginview' %}" style="margin-right: 25px;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>





                                 <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="{% url 'accounts:loginview' %}" style="margin-right: 25px;"><span class="glyphicon glyphicon-log-in" ></span> Login</a></li>
                            </ul>
                        {% endif %}-->


              </ul>
            </div>
          </div>

        </nav>

        {% endblock %}


        <div class="jumbotron text-center" style="height:270px;padding-top:60px;padding-bottom:25px">
<img class="img-responsive" src="{% static 'nitte.png' %}" align="left" width="124" height="136">
               <img class="img-responsive" src="{% static 'nittelogo1.png' %}" align="right" width="124" height="136">
               <img class="img-responsive center-block" src="{% static 'Ktaka_logo.png' %}">

            <h1>Challenge 5</h1>
            <h3>Real Time Record Maintenance</h3>

        </div>

<!-- Description of Real Time Record Maintenance -->

<div id="product" class="panel panel-info">
      <div class="panel-heading">

<p class="lead">Use cases:Land  Records  Management  Through  Use  of
Blockchain</p>
 </div>

 <div class="panel-body">
   <br>
<p>
<code>DESCRIPTION OF USE CASE</code>
  <p>
  The    Revenue    department    of    Government    of    Karnataka    maintains    land    records    in    digital
  form
</p>
  <p>
  The    land    records    are    important    from    a    the    perspective    of    a)
  title    of    a    land    unit    needs    to    be
  confirmed    with    one    owner    and    b)    there    needs    to    be    a    clear    trail    &    record    of    all    transactions    done
  regarding    the    unit
  </p>
  <p>
  The
  land    record    are    used    by    various    other    departments/stakeholders    concerning    a    particular    land
  e.g.    registrar    office    for    sale/registration,    banks/co
  -­‐
  operatives    for    farm    loans,    land    acquisition
  department    for    village/town    extension,    roads,    culverts    etc.
</p>
  <p>
  We
  need    to    have    a    trustworthy    real
  -­‐
  time    record    maintenance    system    capturing    various    attributes
  pertaining    to    a    land
 </p>






<div syle="align:'left' " ;class="container">
 <a href="#demo1" class="btn btn-info" data-toggle="collapse">Know more</a>
  <div id="demo1" class="collapse">
<br>
<code>AS-­IS SCENARIO:</code>
<p>Record of rights, tenancy and crop (RTC) on a land in Karnataka is maintained on an online mutation application named BHOOMI
Change to RTCs due to sale, partition, inheritance, pledge, release, government/court order etc. happen only on BHOOMI without anphysical record keeping/human intervention
The mutation process is initiated at taluka level and then replicated at the state level to establish the record of rights (ROR) at a stalevel
The state level information on land records is shared electronically with different stakeholders for various purposes –
</p>
<p>
 Registration Department – The transaction to transfer the rights except inheritance happens in Sub Registrar Office. KAVERIsystem of the Stamps and Registration department – talks electronically to BHOOMI. This has not only helped prospective buyebut has also gone a long way in enhancing the credibility of the registration department
</p>
<p>
 Banks and Co-­‐operative Institutions – Banks and co-­‐operative institutions are enabled to electronically raise digitally signed requefor pledge or release of any land. This has helped them to access the land records database for confirming ownership, extenowned by the farmer, other liabilities that farmer has and also monitor the status of requests raised by them
</p>
<p>
 Land Acquiring Bodies – BHOOSWADEENA, an automated land acquisition system, talks electronically to BHOOMI, for variouactivities such as village/town extension, roads, culverts, reservoirs, canals, military camps, railways, industries etc., as needed bthe government
</p>
<p>
 Survey Department – A pre-­‐mutation sketch is mandatory and no transaction in sub-­‐registrar offices can happen without the sketcMOJANI, a software for meant for this purpose, if fully integrated with BHOOMI to achieve this objective
</p>
<p>
 Others – Crop details of ROR are used by department of Economics and Statistics, Agriculture and horticulture. Forest departmeuses ROR data for protecting forest land
</p>
<code>TO-­BE SCENARIO</code>
<p>
The information pertaining to a land record (ownership, extent of ownership, farm credit declaration, notification from land
acquisition authorities, government/court orders etc.) shouldn’t be centralized, lying on a single/few servers under the
ownership of only a few parties – BHOOMI, KAVERI, BHOOSWADEENA, MOJANI etc.
</p>
<p>
The information should be readily available to all the interested parties (individuals, banks, registration department, survey
department etc.), with no dependency on a particular stakeholder/owner or seeking information from one entity, with
relevant rights to read/write the right set of information
</p>
<p>
The authencity of the information in such a decentralized scenario is of utmost importance – in spite of the information lying
in a decentralized manner, nobody should be able to modify/edit the information entered previously
Any piece of information appended to the existing set should be agreeable to all the relevant stakeholders
The transactions should happen on a real-­‐time basis, to avoid any situation of two transactions of opposite nature putting
forth their claim on a single asset
The transactions should be traceable and transparent – any changes made to land records should be traceable with the set
of information attached at each step
</p>

   </div>
</div>

      </div>
    </div>





        {% endblock %}

frontend/website1/Project/baseportal/templates/baseportal/landrecord.html
{% extends 'base.html' %}



        {% block navbar %}
        <div class="navbar-wrapper" >
            <div class="container-fluid">


        <nav class="navbar navbar-inverse navbar-fixed-top">

            <a class="navbar-brand" href="#">Real Time Record Maintenance</a>
          <!--<div class="container">
                </div>-->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav navbar-right" style="margin-right:1px">



                            <li class="active"><a href="{% url 'baseportal:homepage' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                        <!--    <li><a href="#product1"><span class="glyphicon glyphicon-shopping-cart"></span> Product</a></li>
                            <li><a href="#about"><i class="fa fa-users"></i> About</a></li>
                            <li><a href="#contact"><i class="fa fa-address-card-o"></i> Contact</a></li>
-->
                    <!--        {% if user.is_authenticated %}
                            <ul class="nav navbar-nav navbar-right">
                             <li><a href="{% url 'accounts:signup' %}"> <span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="{% url 'accounts:loginview' %}" style="margin-right: 25px;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>





                                 <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="{% url 'accounts:loginview' %}" style="margin-right: 25px;"><span class="glyphicon glyphicon-log-in" ></span> Login</a></li>
                            </ul>
                        {% endif %}-->


              </ul>
            </div>
          </div>

        </nav>

        {% endblock %}



<div id="landrecord">
</div>

{% block content %}
<script>
function getDistrict(m)
{
	data={"district":m};
	url="/Project/webapi/taluk/"

	$.ajax({
		method: "GET",
	  dataType: "json",
	  url: url,
	  data: data,
	  success: function(x){
			htm="<option>Select Taluk</option>"
			for (i in x){
				htm+="<option value="+x[i].id+">"+x[i].name+"</option>"
			}
			document.getElementById('id_taluk').innerHTML=htm;
		}
	});
}
function getTaluk(htm)
{

	url="/Project/webapi/grampanchayat/"
	data={"taluk":htm};

	$.ajax({
		method: "GET",
		dataType: "json",
		url: url,
		data: data,
		success: function(y){
			non="<option>Select GP</option>"
			for(i in y)
			{
				non+="<option value="+y[i].id+">"+y[i].name+"</option>"
			}
			document.getElementById('id_gram_panchayat').innerHTML=non;
		}
	});
}
</script>
<form class="form-inline" method='post'>
<br>
<br>
<br>
<br>
	<div clas="form-action">
	{% csrf_token %}
	<table class="table">{{form.as_table}}
    </table>
	<button type="submit" class="btn btn-success btn-sm ">Get Record</button>
</div>
</form>
{% if result is not None %}
{% if result.aadhar == 0 %}
<p>Invalid Information</p>
<script>alert("Invalid Record")</script>
{% else %}
<form class="form-inline" method='post'>
<div clas="form-action">
<table class="table">
	<tr>
		<th>Lot No</th>
		<td>{{result.lotno}}</td>
	</tr>
	<tr>
		<th>Name</th>
		<td>{{result.name}}</td>
	</tr>
	<tr>
		<th>AADHAR</th>
		<td>{{result.aadhar}}</td>
	</tr>
	<tr>
		<th>PAN</th>
		<td>{{result.pan}}</td>
	</tr>
</table>
</div>
</form>
{% endif %}
{% endif %}
{% endblock %}

frontend/website1/Project/baseportal/templates/baseportal/navbar.html
{% extends 'base.html' %}

<script>
{% include 'baseportal/scroll.js' %}
</script>
{% block navbar %}
<div class="navbar-wrapper" >
    <div class="container-fluid">


<nav class="navbar navbar-inverse navbar-fixed-top">

    <a class="navbar-brand" href="#">Smart Water management</a>
  <!--<div class="container">
        </div>-->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">



                    <li class="active"><a href="#home"><span class="glyphicon glyphicon-home"></span> Land Records</a></li>
                <!--    <li><a href="#product1"><span class="glyphicon glyphicon-shopping-cart"></span> Product</a></li>
                    <li><a href="#about"><i class="fa fa-users"></i> About</a></li>
                    <li><a href="#contact"><i class="fa fa-address-card-o"></i> Contact</a></li>
                    -->

                    {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                     <li><a href="{% url 'accounts:signup' %}"> <span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'accounts:loginview' %}" style="margin-right: 25px;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>


                   <!--     <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </ul>-->

{% else %}

                        <!--<li><a href="{% url 'accounts:loginview' %}">Log In</a></li>-->
                         <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'accounts:loginview' %}" style="margin-right: 25px;"><span class="glyphicon glyphicon-log-in" ></span> Login</a></li>
                    </ul>
                {% endif %}


        <!--<li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>-->
      </ul>
    </div>
  </div>

</nav>

{% endblock %}